# -*coding:UTF-8*-
def askcontinue():
    input('按任意键继续......')

print('Tktext使用及引用须知\n\n')
print('使用前或准备使对此作品进行引用前，请阅读这个须知！')
print('未经允许，不可抄袭！')
print('如果您的条件不允许使用Tktext，那请不要使用。')
askcontinue()
print('1）使用最低要求')
print('您要使用它，必须要满足以下系统要求：')
print('操作系统：Windows Python版本：3.x ')
print('要获得最佳使用体验，请满足以下要求：')
print('操作系统：Windows Python版本：3.8 ')
askcontinue()
print('2）引用的相关声明')
print('引用这个项目需要经过作者（zhihongwang250）的同意，并且在该作品的建议栏里进行说明。')
print('未经作者的允许，严禁引用本作品的任何环节（包括源码，说明等）！')
askcontinue()
exit()
